### ISSUE TITLE
Add home link to logo

### ISSUE THREAD

**Issue by Khyati41** [Dharmik48/seeit#46] opened 2022-08-14 12:21 UTC

**Comment by Dharmik48** [comment] 2022-08-14 12:22
Would you like to work on this issue?

**Comment by Khyati41** [comment] 2022-08-14 12:23
Yes

**Comment by Dharmik48** [comment] 2022-08-14 12:23
Alright! I'll assign this to you!

**Comment by AngeloTree** [comment] 2022-08-15 00:43
Hey, I am interested in working on this task!

**Comment by Dharmik48** [comment] 2022-08-15 05:31
> Hey, I am interested in working on this task!

I extremely sorry @AngeloTree, but the issue is already assigned to @Khyati41.

You can check out other issues on any of these repos which are not assigned to anyone yet:

- https://github.com/Dharmik48/notes-react-firebase-v2.0/issues
- https://github.com/Dharmik48/todo-list-app/issues

**Comment by pokhrelanmol** [comment] 2022-08-24 03:16
why this issue is still not resolved ?

**Comment by Dharmik48** [comment] 2022-08-24 14:50
> why this issue is still not resolved ?

Oh, my bad😅 I forgot to close this issue, Thanks for the reminder!

**Closed as completed by Dharmik48** 2022-08-24 14:50 UTC
Labels: bug, good first issue, EddieHub:good-first-issue
